name: 'apt-repo-action'
description: 'Download GitHub organization to a apt repo'
inputs:
  token:
    required: true
  organization:
    required: true
  output:
    required: true
runs:
  using: "composite"
  steps:
    - name: Checkout
      uses: actions/checkout@v3
      with:
        repository: radxa-repo/apt-repo-action
        path: .apt-repo-action
    - name: Run
      shell: bash
      run: |
        dotnet run -c Release --project ./.apt-repo-action/apt-repo.csproj -- ${{ inputs.token }} ${{ inputs.organization }} ${{ inputs.output }}
        rm -rf ./.apt-repo-action